### PR TITLE
CNMF-E setting long file/folder names update

### PR DESCRIPTION
**Pull request by bahanonu**
- MATLAB has a 63 character limit for script names, truncating cnmfe setting names over this limit to comply.
- Add in the name of the original settings file used in a 1st line comment instead of in the filename to cause less trucation of folder name.

### CODE REVIEW

**Comment by bahanonu** [comment]
@omidm7

See this pull request that should fix the issue caused by the long folder name in your example—MATLAB has a 63 character limit on script names. I had previously only applied filename truncating to when user manually selected settings file, but applies in both cases now.

Response to https://github.com/bahanonu/calciumImagingAnalysis/pull/17#issuecomment-483378252.

**Comment by omidm7** [comment]
Great, thank you!

**Comment by bahanonu** [comment]
@omidm7

👍 I assume it's working fine and I can merge?

**Comment by bahanonu** [comment]
@omidm7

👍 I assume it's working fine on your end and I can merge?

**Comment by omidm7** [comment]
Sorry, I was waiting for the merge. How do I apply the fix before you merge it?

**Comment by bahanonu** [comment]
If you are using the GitHub desktop app, see below. Select `Current branch` then `Pull requests` and selecting this pull request will switch you to the appropriate branch. You can then select `master` in `Branches` to go back to the master branch after I've merged.

image

Else on the pull request thread, select `bahanonu/functionUpdates` which will take you to the branch URL page and download from there.
image

**Comment by omidm7** [comment]
Hey,
So I downloaded the new @calciumImagingAnalysis from the function updates, and now I am getting this error when trying to add new folders:
image
Here is an image of all the folders I'm trying to add:
image

**Comment by bahanonu** [comment]
Added the `subjectRegexp` property, seems didn't sync between the private and public repos. Let me know if works fine on your end now.

**Comment by omidm7** [comment]
👌🏼We're back in business! I'll keep you updated when the cnmf-e goes through. 
Thanks man.
Omid

**Comment by omidm7** [comment]
Biafra,
Here is the error code I get when running viewMatchObjBtwnSessions. Is this error resulting because my sessions are not all the same size?

[Untitled.pdf](https://github.com/bahanonu/calciumImagingAnalysis/files/3086586/Untitled.pdf)

**Pull request merged**
