### PR TITLE
Updates to CNMF-E related functions and other misc. updates

### PR DESCRIPTION
**Pull request by bahanonu**
- Expanded CNMF-E wrapper `computeCnmfeSignalExtraction` to include many of the options as part of the getOptions construct and added descriptions if missing from original demo script.
- New method of entering settings for CNMF-E using scripted opening of Matlab editor, allows more user friendly editing of settings with all descriptions as in function. Saves a temporary file for each run so users can go back and check.
- `viewObjmaps` (added last pull request) is a quick method to visualize outputs from cell extraction. Simplification of `viewCreateObjmaps` for quick checking.
- Some misc other changes.

### CODE REVIEW

**Comment by omidm7** [comment]
Hey Biafra, thanks for all the updates! I noticed all the small changes, and they're great. Also, thanks for adding the viewObj feature.
Question: What is the difference between the top left panel and the bottom right? I believe the bottom right represents all the cells that I have manually accepted. But what are the colored cells in the top left?

image

**Comment by bahanonu** [comment]
@omidm7 

Great to hear! The top-left just shows all the manually choosen cells (colored in various colors, 'validManual' at end of top title indicates that it is showing manually sorted outputs as opposed to automatic, etc.) and non-cells (colored in grays) while the bottom-right shows the colored cells from the top-left but overlaying their outlines onto the raw (or dF/F depending on user input) movie. I'll make the titles so that's clearer for users.

I'll make an update to viewObj that will allow showing of the session numbers/IDs for all the cells for that day as we'd talked about.

**Comment by omidm7** [comment]
Hi Biafra, using this latest update, I encountered the following error when trying to run cnmf-e. 

image

I looked in the 'private' directory and there are no settings folder in there.
Omid

**Comment by bahanonu** [comment]
@omidm7 

Thanks for the heads up, I'll make the change so it checks that the settings sub-folder is present in the private folder. Check https://github.com/bahanonu/calciumImagingAnalysis/pull/17 later today.

**Comment by bahanonu** [comment]
If you manually create the `private/settings` folder, that should solve your issue until I push the commit.

**Pull request merged**
