### PR TITLE
signalSorter asynchronous calls for cell sorting large movies and misc. function updates

### PR DESCRIPTION
**Pull request by bahanonu**
- To improve use of signalSorter with very large movies and especially those stored on servers or Oak, added asynchronous calls to create the trasient cut movies and images for `nSignalsLoadAsync` # of future signals so user can sort while in the background new signals are loaded.
- This is only on when options `readMovieChunks = 0` and `preComputeImageCutMovies = 0` are set.
- Additional changes to other functions, see commits.

### CODE REVIEW

**Comment by omidm7** [comment]
Hi Biafra, I think there may be a new bug with the crop function?
For example: I crop the video during preprocessing like this >  
image
And the output file after preprocessing has the crop regexpress, but the video is still ~250x350. And when I use the crop regexpress to do CNMFe, it uses the original video size.

For now I will manually crop the videos in imageJ.
Omid

**Comment by bahanonu** [comment]
@omidm7 
Are you referring to the crop requested in `modelPreprocessMovie` pre-processing function? That only crops for motion correction but applies the registration transform coordinates on the original movie without cropping. In general, I don't crop the actual movie size (makes cross-session alignment easier to have all movies be the same size), rather I add black borders, see

https://github.com/bahanonu/calciumImagingAnalysis#manual-movie-cropping-with-modelmodifymovies

cheers,
-Biafra

**Comment by omidm7** [comment]
Ah gotcha!

**Comment by bahanonu** [comment]
@tigsch

Try the updated signalSorter on this pull request, tested on your dataset and the slow increase in time between cell extraction outputs being picked is now gone (see below for timing).

image

**Pull request merged**
