### PR TITLE
Improved Miji start/exit handling, README updates, etc.

### PR DESCRIPTION
**Pull request by bahanonu**
- `manageMiji` function to manage starting and exiting Miji that controls more for issues that might be encountered in different Matlab and Miji versions.

### CODE REVIEW

**Comment by bahanonu** [comment]
@omidm7

Added in extra set of figures to `viewObjmaps` so that it quickly shows the within session ID for each cell. The cellmap automatically has zoom enabled so users can get a better look for dense cell regions.

image

**Comment by omidm7** [comment]
That looks great, thanks so much, Biafra!

**Comment by bahanonu** [comment]
@omidm7 
See current master branch for update re: settings folder.

**Comment by omidm7** [comment]
Perfect, it's working now. 
I'm actually trying to extract signals from cross-session aligned stacks, for the first time. I'll let you know how that goes. :)
Omid

**Comment by omidm7** [comment]
Ok. I spoke a bit too soon. Any idea what's causing this error? 

[Untitled.pdf](https://github.com/bahanonu/calciumImagingAnalysis/files/3081702/Untitled.pdf)

**Pull request merged**
